config/routes.rb
SampleProject::Application.routes.draw do
  resources :users do
    resources :microposts, :only => [:index]

    member do
      get :following, :followers
    end
  end
  resources :sessions,      :only => [:new, :create, :destroy]
  resources :microposts,    :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'

  root :to => 'pages#home'

end

app/models/user.rb
require 'digest'

class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation

  has_many :microposts, :dependent => :destroy
  has_many :relationships, :foreign_key => 'follower_id', :dependent => :destroy
  has_many :following, :through => :relationships, :source => :followed
  has_many :reverse_relationships, :foreign_key => 'followed_id', :class_name => 'Relationship', :dependent => :destroy
  has_many :followers, :through => :reverse_relationships, :source => :follower

  email_regexp = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name,     :presence     => true,
                       :length       => {:maximum => 50}
  validates :email,    :presence     => true,
                       :format       => {:with => email_regexp},
                       :uniqueness   => {:case_sensitive => false}
  validates :password, :presence     => true,
                       :confirmation => true,
                       :length       => {:within => 6..40}

  before_save :encrypt_password

  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def feed
    Micropost.from_users_followed_by(self)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end

  def following?(followed)
    self.relationships.find_by_followed_id(followed)
  end

  def follow!(followed)
    self.relationships.create!(:followed_id => followed.id)
  end

  def unfollow!(followed)
    self.relationships.find_by_followed_id(followed).destroy
  end

  private

  def encrypt_password
    self.salt = make_salt unless has_password?(password)
    self.encrypted_password = encrypt(password)
  end

  def encrypt(string)
    secure_hash("#{salt}--#{string}")
  end

  def make_salt
    secure_hash("#{Time.now.utc}--#{password}")
  end

  def secure_hash(string)
    Digest::SHA2.hexdigest(string)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate,  :except => [:show, :new, :create]
  before_filter :correct_user,  :only => [:edit, :update]
  before_filter :admin_user,    :only => :destroy
  before_filter :not_logged_in, :only => [:new, :create]

  def index
    @title = 'Members'
    @users = User.paginate(:page => params[:page])
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(:page => params[:page], :per_page => 10)
    @title = "User Profile: #{@user.name}"
  end

  def new
    @user = User.new
    @title = 'Sign Up'
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      sign_in @user
      flash[:success] = 'Welcome to the Sample App!'
      redirect_to @user
    else
      @user.password = nil
      @user.password_confirmation = nil
      @title = 'Sign Up'
      render 'new'
    end
  end

  def edit
    @title = 'Edit Profile'
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:success] = 'Profile updated.'
      redirect_to @user
    else
      @title = 'Edit Profile'
      render 'edit'
    end
  end

  def destroy
    user = User.find(params[:id])
    if user == current_user
      flash[:error] = 'You may not delete yourself.'
      redirect_to users_path
    else
      user.destroy
      flash[:success] = 'User deleted.'
      redirect_to users_path
    end
  end

  def following
    show_follow(:following)
  end

  def followers
    show_follow(:followers)
  end

  private

  def correct_user
    @user = User.find(params[:id])
    unless current_user?(@user)
      flash[:notice] = 'You may only edit your own profile.'
      redirect_to(root_path)
    end
  end

  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end

  def not_logged_in
    redirect_to(root_path) if signed_in?
  end

  def show_follow(action)
    @title = action.to_s.capitalize
    @user = User.find(params[:id])
    @users = @user.send(action).paginate(:page => params[:page], :per_page => 20)
    render 'show_follow'
  end
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = {:size => 50})
    gravatar_image_tag(user.email.downcase, :alt => user.name,
                                            :class => 'gravatar',
                                            :gravatar => options)
  end
end

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', :object => f.object %>
<div class="field">
  <%= f.label :name %><br/>
  <%= f.text_field :name, :autofocus => '' %>
</div>
<div class="field">
  <%= f.label :email %><br/>
  <%= f.text_field :email %>
</div>
<div class="field">
  <%= f.label :password %><br/>
  <%= f.password_field :password %>
</div>
<div class="field">
  <%= f.label :password_confirmation, 'Confirm Password' %><br/>
  <%= f.password_field :password_confirmation %>
</div>

app/views/users/_follow.html.erb
<%= form_for current_user.relationships.build(:followed_id => @user.id), :remote => true do |f| %>
<div class="actions"><%= f.hidden_field :followed_id %><%= f.submit 'Follow' %></div>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
<div id="follow-form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
</div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for current_user.relationships.find_by_followed_id(@user), :html => {:method => :delete}, :remote => true do |f| %>
<div class="actions"><%= f.submit 'Unfollow' %></div>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, :size => 30 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? %>
    (<%= link_to 'delete', user, :method => :delete, :confirm => "Are you sure you want to delete #{user.name}?", :title => "Delete #{user.name}" %>)
  <% end %>
</li>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>

<%= form_for(@user) do |f| %>
<%= render 'fields', :f => f %>
<div class="actions">
  <%= f.submit 'Update' %>
</div>
<% end %>
<div>
  <%= gravatar_for @user %>
  <a href="http://gravatar.com/emails">Change</a>
</div>

app/views/users/index.html.erb
<h1>Member List</h1>

<%= will_paginate %>

<ul class="users">
<%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for(@user) do |f| %>
<%= render 'fields', :f => f %>
<div class="actions">
  <%= f.submit 'Sign Up' %>
</div>
<% end %>

app/views/users/show.html.erb
<table id="profile" summary="Profile Information for User <%= @user.name %>">
<tr>
  <td id="main">
    <h1>
      <%= gravatar_for @user %>
      <%= @user.name %>
    </h1>
    <%= render @microposts %>
    <%= will_paginate @microposts %>
  </td>
  <td id="sidebar">
  <p class="round">
    <b>Name:</b> <%= @user.name %><br/>
    <b>URL:</b>  <%= link_to user_path(@user), @user %><br/>
    <b>Microposts:</b> <%= link_to @user.microposts.count, user_microposts_path(@user) %>
  </p>
  </td>
</tr>
</table>

app/views/users/show_follow.html.erb
<table>
<tr>
  <td id="main">
    <h1><%= @title %></h1>

    <% unless @users.empty? %>
    <ul class="users">
      <%= render @users %>
    </ul>
    <%= will_paginate @users %>
    <% end %>
  </td>
  <td id="sidebar">
  <p class="round">
    <b>Name:</b> <%= @user.name %><br/>
    <b>URL:</b>  <%= link_to user_path(@user), @user %><br/>
    <b>Microposts:</b> <%= link_to @user.microposts.count, user_microposts_path(@user) %><br/>
    <%= render 'shared/stats' %>
    <% unless @users.empty? %>
      <% @users.each do |user| %>
        <%= link_to gravatar_for(user, :size => 30), user %>
      <% end %>
    <% end %>
  </p>
  </td>
</tr>
</table>