config/routes.rb
SampleProject::Application.routes.draw do
  resources :users do
    resources :microposts, :only => [:index]

    member do
      get :following, :followers
    end
  end
  resources :sessions,      :only => [:new, :create, :destroy]
  resources :microposts,    :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'

  root :to => 'pages#home'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
<h2><%= pluralize(object.errors.count, 'error') %>
  prohibited this <%= object.class.to_s.underscore.humanize.downcase %>
  from being saved:</h2>
<p>There were problems with the following fields:</p>
<ul>
<% object.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>

app/views/shared/_feed.html.erb
<% unless @feed_items.empty? %>
  <%= render :partial => 'shared/feed_item', :collection => @feed_items %>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<article>
<div><%= link_to gravatar_for(feed_item.user, :size => 30), feed_item.user %>
<%= link_to feed_item.user.name, feed_item.user %></div>
<p class="content"><%= wrap(feed_item.content) %></p>
<p class="timestamp">Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
<% if current_user?(feed_item.user) %>
<span class="delete-link">(<%= link_to 'delete', feed_item, :method => :delete, :confirm => 'Are you sure you want to delete your post?' %>)</span>
<% end %></p>
</article>

app/views/shared/_home_signed_in.html.erb
<table id="front">
<tr>
  <td id="main">
    <h1>What's new?</h1>
    <%= render 'shared/micropost_form' %>
    <%= render 'shared/feed' %>
  </td>
  <td id="sidebar">
    <p class="round">
      <%= render 'shared/user_info' %>
      <%= render 'shared/stats' %>
    </p>
  </td>
</tr>
</table>

app/views/shared/_home_signed_out.html.erb
<h1>Sample App</h1>
<p>This is the home page for the
<a href="http://railstutorial.org/">Rails Tutorial</a> sample application.</p>
<%= link_to 'Sign up now!', signup_path, :class => 'signup_button round' %>

app/views/shared/_micropost_form.html.erb
<%= form_for @micropost do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit 'Post!' %>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<a id="following" href="<%= following_user_path(@user) %>"><%= @user.following.count %> following</a><br/>
<a id="followers" href="<%= followers_user_path(@user) %>"><%= pluralize(@user.followers.count, 'follower') %></a><br/>

app/views/shared/_user_info.html.erb
  <%= gravatar_for current_user, :size => 30 %>
  <a href="<%= user_path(current_user) %>">
  <span class="user_name">
    <%= current_user.name %>
  </span></a><br/>
  <span class="microposts">
    <%= pluralize(current_user.microposts.count, 'micropost') %>
  </span><br/>